---
apiVersion: v1
kind: Service
metadata:
  name: spring-cloud-config-server
  namespace: beta-botcatalogs
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: spring-cloud-config-server
